#!/usr/bin/env python3
"""
sync-shared.py -- regenerate the blocks that several plugin files must carry
verbatim, from one source file each.

Every agent, command and the skill needs the same "locate the toolkit" instructions.
Hand-copied, those drift (see tasks/lessons.md, Active Rule 1), and a stale copy
sends an agent to a path that no longer exists. So the text lives once, in
scripts/shared/<name>.md, and each file marks where it goes:

    <!-- toolkit:begin (generated ...) -->
    ...replaced on every run...
    <!-- toolkit:end -->

Run from the repo root:
  python3 scripts/sync-shared.py           rewrite every marked block
  python3 scripts/sync-shared.py --check   exit 1 if any block differs (verify.py uses this)
"""

from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHARED = os.path.join(ROOT, "scripts", "shared")
SCAN_DIRS = ("agents", "commands", "skills")
BEGIN = "<!-- {name}:begin (generated by scripts/sync-shared.py from scripts/shared/{name}.md -- edit there, then run it) -->"
END = "<!-- {name}:end -->"


def blocks():
    return sorted(f[:-3] for f in os.listdir(SHARED) if f.endswith(".md"))


def targets():
    for d in SCAN_DIRS:
        for dirpath, _, files in os.walk(os.path.join(ROOT, d)):
            for f in sorted(files):
                if f.endswith(".md"):
                    yield os.path.join(dirpath, f)


def render(text, name, body):
    """Return (new_text, count) with every `name` block replaced by body."""
    rx = re.compile(r"<!-- %s:begin[^>]*-->\n.*?<!-- %s:end -->" % (re.escape(name), re.escape(name)), re.S)
    replacement = BEGIN.format(name=name) + "\n" + body.rstrip("\n") + "\n" + END.format(name=name)
    return rx.subn(lambda _m: replacement, text)


def main(argv):
    check = "--check" in argv
    stale, total = [], 0
    for name in blocks():
        with open(os.path.join(SHARED, name + ".md"), encoding="utf-8") as fh:
            body = fh.read()
        for path in targets():
            with open(path, encoding="utf-8") as fh:
                text = fh.read()
            new, n = render(text, name, body)
            if not n:
                continue
            total += n
            if new != text:
                rel = os.path.relpath(path, ROOT)
                stale.append(f"{rel} ({name})")
                if not check:
                    with open(path, "w", encoding="utf-8") as fh:
                        fh.write(new)
    if check:
        if stale:
            print("stale shared blocks: " + ", ".join(stale))
            print("run: python3 scripts/sync-shared.py")
            return 1
        print(f"{total} shared block(s) in sync")
        return 0
    print(f"{total} shared block(s); rewrote {len(stale)}" + (": " + ", ".join(stale) if stale else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
